export const QueryKeys = {
  AdjustmentLog: "ADJUSTMENT_LOG",
  AnalyticDashboard: "ANALYTIC_DASHBOARD",
  Attribute: "ATTRIBUTE",
  AttributeValue: "ATTRIBUTE_VALUE",
  Category: "CATEGORY",
  DailyViewStats: "DAILY_VIEW_STATS",
  Enum: "ENUM",
  ExportLog: "EXPORT_LOG",
  ImportLog: "IMPORT_LOG",
  Inventory: "INVENTORY",
  Model: "MODEL",
  Notification: "NOTIFICATION",
  Order: "ORDER",
  OrderReturnRequest: "ORDER_RETURN_REQUEST",
  Payment: "PAYMENT",
  Product: "PRODUCT",
  RevenueProfitDailyStats: "PROFIT_REVENUE_DAILY_STATS",
  RevenueProfitSummaryStats: "PROFIT_REVENUE_SUMMARY_STATS",
  Sku: "SKU",
  Stock: "STOCK",
  ViewSummaryStats: "VIEW_SUMMARY_STATS",
  Warehouse: "WAREHOUSE",
};
