import Layout from '@/components/common/sharing/layout';
import { ColorModeProvider } from '@/contexts/ColorModeContext';
import { CssBaseline } from '@mui/material';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <ColorModeProvider>
        <CssBaseline />
        <body className={inter.className}>
          <Layout>{children}</Layout>
        </body>
      </ColorModeProvider>
    </html>
  );
}
