import { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { GoogleOAuthProvider } from '@react-oauth/google';

import { AuthStoreProvider } from '@/providers/auth-store-provider';
import { ColorModeProvider } from '@/contexts/ColorModeContext';
import Providers from './providers';

import { CssBaseline } from '@mui/material';

const inter = Inter({
  weight: ['400', '600', '700', '800', '900'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <GoogleOAuthProvider clientId='74957006221-6mm4u0inm5drqgrt1hpoiagugbuhoav6.apps.googleusercontent.com'>
      <html lang='en'>
        <ColorModeProvider>
          <CssBaseline />
          <body className={inter.className}>
            <AuthStoreProvider>
              <Providers>{children}</Providers>
            </AuthStoreProvider>
          </body>
        </ColorModeProvider>
      </html>
    </GoogleOAuthProvider>
  );
}
