name: Deploy Backend to VPS

on:
  push:
    branches: ['main']
    paths:
      - 'geardn-server/**' # Chỉ chạy khi sửa code backend

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./geardn-server # Trỏ đúng vào thư mục backend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/geardn-server:latest

  deploy-to-vps:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy docker-compose to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.HOST_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: './geardn-server/docker-compose.yml'
          target: '/var/www/geardn-server/' # Đã sửa target cho đúng
          # strip_components: 1 # Bỏ cái này đi để nó copy đúng đường dẫn

      - name: SSH into VPS and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.HOST_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/geardn-server
            # Pull image mới nhất về
            docker pull ${{ secrets.DOCKER_USERNAME }}/geardn-server:latest

            # Restart lại container với image mới
            docker compose up -d --remove-orphans

            # Xóa các image rác cũ cho sạch ổ cứng
            docker image prune -f
